import { hamburger } from "./features/hamburger.js"
import { typewriter } from "./features/typewriter.js"
import { smoothScroll } from "./features/smoothscroll.js"
import { animationsTech } from "./features/animations.js"
import { animationsCard } from "./features/animations.js"
